spring.application.name=gerenciamendodetarefas


# Ativa o painel web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Define uma URL fixa para o banco (evita que o Spring gere um nome aleatório a cada restart)
spring.datasource.url=jdbc:h2:mem:gerenciamento
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=bifewagyu
spring.datasource.password=
